### ISSUE TITLE
unused args (texture = TRUE)

### ISSUE THREAD

**Issue by ayor-dns** [Pecners/rayshader_portraits#2]
Any idea why I got this error when trying to do render_highquality() :

`Error in rayrender::obj_model(cache_filename, x = -bbox_center[1], y = -bbox_center[2],  : 
  unused arguments (texture = TRUE)`

I didn't change your code. I'll run it with latest R vrsion (4.2.2) and all package are up to date.
I tried : `remotes::install_github("tylermorganwall/rayrender")` but didn't worked.

**Comment by Pecners** [comment]
I haven't tracked down exactly why this error is thrown when following my code, but others have said installing the latest dev versions of {rayrender} AND {rayshader} solved it. So, try `remotes::install_github("tylermorganwall/rayshader")` as well.

**Comment by ayor-dns** [comment]
That worked ! 
thank you, your help is much appreciated !
